<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <form method="post">
                    <?php echo $this->partial('/car/modification/_select.phtml', [
                        'brands' => $brands
                    ]) ?>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default">Search</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>