<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">Шины и диски</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <?php foreach ($this->items as $item) { ?>
                    <?php if (!isset($item['float']) || $item['float'] == 'left') { ?>
                        <?php
                        $id = isset($item['id']) ? $item['id'] : '';
                        $isActive = ($id==$this->activeItemId);
                        $label = isset($item['label']) ? $item['label'] : '';
                        ?>
                        <?php if (isset($item['dropdown'])) { ?>
                            <li class="dropdown <?php if ($isActive) { ?>active<?php } ?>">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <?= $this->translate($this->escapeHtml($label)) ?>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <?php foreach ($item['dropdown'] as $dropdownItem) { ?>
                                        <?php
                                        $link = isset($dropdownItem['link']) ? $dropdownItem['link'] : '#';
                                        $label = isset($dropdownItem['label']) ? $dropdownItem['label'] : '';
                                        ?>
                                        <li>
                                            <a href="<?php echo $this->escapeHtml($link) ?>"><?= $this->translate($this->escapeHtml($label)) ?></a>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </li>
                        <?php } else { ?>
                            <?php $link = isset($item['link']) ? $item['link'] : '#'; ?>
                            <li <?php if ($isActive) { ?>class="active"<?php } ?>>
                                <a href="<?php echo $this->escapeHtml($link) ?>"><?php echo $this->translate($this->escapeHtml($label)) ?></a>
                            </li>
                        <?php } ?>
                    <?php } ?>
                <?php } ?>
            </ul>
            <div class="col-sm-3 col-md-3">
                <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search" name="q">
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <?php foreach ($this->items as $item) { ?>
                    <?php if (isset($item['float']) && $item['float'] == 'right') { ?>
                        <?php
                        $id = isset($item['id']) ? $item['id'] : '';
                        $isActive = ($id==$this->activeItemId);
                        $label = isset($item['label']) ? $item['label'] : '';
                        ?>
                        <?php if (isset($item['dropdown'])) { ?>
                            <li class="dropdown <?php if ($isActive) { ?>active<?php } ?>">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <?= $this->translate($this->escapeHtml($label)) ?>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <?php foreach ($item['dropdown'] as $dropdownItem) { ?>
                                        <?php
                                        $link = isset($dropdownItem['link']) ? $dropdownItem['link'] : '#';
                                        $label = isset($dropdownItem['label']) ? $dropdownItem['label'] : '';
                                        ?>
                                        <li>
                                            <a href="<?php echo $this->escapeHtml($link) ?>"><?php echo $this->translate($this->escapeHtml($label)) ?></a>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </li>
                        <?php } else { ?>
                            <?php $link = isset($item['link']) ? $item['link'] : '#'; ?>
                            <li <?php if ($isActive) { ?>class="active"<?php } ?>>
                                <a href="<?php echo $this->escapeHtml($link) ?>"><?= $this->translate($this->escapeHtml($label)) ?></a>
                            </li>
                        <?php } ?>
                    <?php } ?>
                <?php } ?>
            </ul>
        </div>
    </div>
</nav>