<div class="row select-modification">
    <div class="col-md-6">
        <div class="form-group">
            <label>Марка</label>
            <select class="form-control select2">
                <option value="0">Выберите марку</option>
                <option value="1">Audi</option>
                <option value="2">BMW</option>
                <option value="3">Mercedes</option>
            </select>
        </div>
        <div class="form-group">
            <label>Поколение</label>
            <select class="form-control select2">
                <option value="0">Выберите марку</option>
                <option value="1">Audi</option>
                <option value="2">BMW</option>
                <option value="3">Mercedes</option>
            </select>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label>Модель</label>
            <select class="form-control select2">
                <option value="0">Выберите марку</option>
                <option value="1">Audi</option>
                <option value="2">BMW</option>
                <option value="3">Mercedes</option>
            </select>
        </div>
        <div class="form-group">
            <label>Модификация</label>
            <select class="form-control select2">
                <option value="0">Выберите марку</option>
                <option value="1">Audi</option>
                <option value="2">BMW</option>
                <option value="3">Mercedes</option>
            </select>
        </div>
    </div>
</div>