<div class="row select-modification">
    <div class="col-md-6">
        <div class="form-group">
            <label>Марка</label>
            <select class="form-control select2">
                <option value="0">Выберите марку</option>
                <?php foreach ($brands as $brand) { ?>
                    <option value="<?= $brand->getId() ?>"><?= $brand->getName() ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="form-group">
            <label>Поколение</label>
            <select class="form-control select2">
                <option value="0">Выберите поколение</option>
            </select>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label>Модель</label>
            <select class="form-control select2">
                <option value="0">Выберите модель</option>
            </select>
        </div>
        <div class="form-group">
            <label>Модификация</label>
            <select class="form-control select2">
                <option value="0">Выберите модификацию</option>
            </select>
        </div>
    </div>
</div>